version: '3.9'
services:
  app:
    container_name: shokai
    image: ghcr.io/yude/shokai:main
    build: .
    volumes:
      - type: bind
        source: ./config.toml
        target: /app/config.toml
    ports:
      - 3000:3000
    restart: always